insert into  IPTREATMENT_PACKAGES( AILMENT_CATEGORY, COST, TEST_DETAILS,TREATMENT_DURATION,TREATMENT_PACKAGE_NAME  ) Values ( 'Urology', 4000,  'UPT1, UPT2',4, 'Package 1');
insert into  IPTREATMENT_PACKAGES( AILMENT_CATEGORY, COST, TEST_DETAILS,TREATMENT_DURATION,TREATMENT_PACKAGE_NAME  ) Values ( 'Orthopaedics', 2500,  'OPT1, OPT2',4, 'Package 1');
insert into  IPTREATMENT_PACKAGES( AILMENT_CATEGORY, COST, TEST_DETAILS,TREATMENT_DURATION,TREATMENT_PACKAGE_NAME  ) Values ( 'Urology', 5000,  'UPT3, UPT4',6, 'Package 2'); 
insert into  IPTREATMENT_PACKAGES( AILMENT_CATEGORY, COST, TEST_DETAILS,TREATMENT_DURATION,TREATMENT_PACKAGE_NAME  ) Values ( 'Orthopaedics', 3000,  'OPT3, OPT4',6, 'Package 2');
insert into  SPECIALIST_DETAIL(AREA_OF_EXPERTISE, CONTACT_NUMBER, EXPERIENCE_IN_YEARS, NAME) Values ( 'Orthopaedics', '1234569870',4,'Dr. Ramesh Sharma');
insert into  SPECIALIST_DETAIL(AREA_OF_EXPERTISE, CONTACT_NUMBER, EXPERIENCE_IN_YEARS, NAME) Values ( 'Urology', '1456328970',3,'Dr. Faisal Sayyed');
insert into  SPECIALIST_DETAIL(AREA_OF_EXPERTISE, CONTACT_NUMBER, EXPERIENCE_IN_YEARS, NAME) Values ( 'Orthopaedics', '2365014789',12,'Dr. Veena Tripathi');
insert into  SPECIALIST_DETAIL(AREA_OF_EXPERTISE, CONTACT_NUMBER, EXPERIENCE_IN_YEARS, NAME) Values ( 'Urology', '3265897410',15,'Dr. Vineet Joshi');

