insert into insurer_detail(insurance_amount_limit, insurer_name, insurer_package_name , disbursement_duration) values(3000, 'Insurer1', 'Ipackage1',10);
insert into insurer_detail(insurance_amount_limit, insurer_name, insurer_package_name , disbursement_duration) values(2000, 'Insurer2', 'Ipackage2',12);
insert into insurer_detail(insurance_amount_limit, insurer_name, insurer_package_name , disbursement_duration) values(7000, 'Insurer3', 'Ipackage3',10);
insert into insurer_detail(insurance_amount_limit, insurer_name, insurer_package_name , disbursement_duration) values(9000, 'Insurer4', 'Ipackage4',11);
insert into insurer_detail(insurance_amount_limit, insurer_name, insurer_package_name , disbursement_duration) values(4000, 'Insurer5', 'Ipackage5',10);
insert into insurer_detail(insurance_amount_limit, insurer_name, insurer_package_name , disbursement_duration) values(6000, 'Insurer6', 'Ipackage6',13);
insert into insurer_detail(insurance_amount_limit, insurer_name, insurer_package_name , disbursement_duration) values(1500, 'Insurer7', 'Ipackage7',7);
insert into insurer_detail(insurance_amount_limit, insurer_name, insurer_package_name , disbursement_duration) values(6600, 'Insurer8', 'Ipackage8',10);
insert into insurer_detail(insurance_amount_limit, insurer_name, insurer_package_name , disbursement_duration) values(10000, 'Insurer9', 'Ipackage9',10);
insert into initiate_claim(ailment,balance,insurer_amount_limit,insurer_name,patient_id,patient_name,status,treatment_cost,treatment_package_name) values ('Urology',3000,2000,'Insurer2',2,'Sheldon Cooper','Completed',5000,'package2');
